version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: cypress
    versions:
    - 7.2.0
  - dependency-name: "@storybook/addon-links"
    versions:
    - 6.2.7
    - 6.2.9
  - dependency-name: "@types/classnames"
    versions:
    - 2.3.1
  - dependency-name: typescript
    versions:
    - 4.2.4
  - dependency-name: "@storybook/addon-actions"
    versions:
    - 6.2.7
    - 6.2.8
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.21.0
    - 4.22.0
  - dependency-name: next-pwa
    versions:
    - 5.2.9
  - dependency-name: "@storybook/addon-knobs"
    versions:
    - 6.2.7
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.2
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.2.7
  - dependency-name: "@storybook/react"
    versions:
    - 6.2.4
